stages:
- name: Test
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: echo "2. Test Stage"
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      tag: yswwhf/jenkins-demo::${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: kubectl apply -f k8s.yaml --record
timeout: 60
notification: {}
