stages:
- name: Test
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: echo "2. Test Stage"
- name: Build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: docker build -t yswwhf/jenkins-demo .
- name: Push
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        docker login -u yswwhf -p asus+0457
        docker push yswwhf/jenkins-demo
- name: Deploy
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: kubectl apply -f k8s.yaml --record
timeout: 60
